"""empty message

Revision ID: c8f6ac25c74f
Revises: 
Create Date: 2020-12-11 13:43:46.553681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f6ac25c74f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('senha', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('enquete',
    sa.Column('id_enquete', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=200), nullable=False),
    sa.Column('data_enquete', sa.DateTime(), nullable=False),
    sa.Column('usuario_enquete', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_enquete'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_enquete')
    )
    op.create_table('post',
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('localizacao', sa.String(length=40), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('imagem', sa.String(length=50), nullable=False),
    sa.Column('data_post', sa.DateTime(), nullable=False),
    sa.Column('usuario_post', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_post'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_post')
    )
    op.create_table('comentario',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('curtida', sa.Boolean(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=True),
    sa.Column('data_comentario', sa.DateTime(), nullable=False),
    sa.Column('usuario_comentario', sa.Integer(), nullable=False),
    sa.Column('usuario_post', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_comentario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['usuario_post'], ['post.id_post'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('resposta_enquete',
    sa.Column('id_resposta_enquete', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=200), nullable=False),
    sa.Column('enquete_resposta', sa.Integer(), nullable=False),
    sa.Column('usuario_resposta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enquete_resposta'], ['enquete.id_enquete'], ),
    sa.ForeignKeyConstraint(['usuario_resposta'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_resposta_enquete')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta_enquete')
    op.drop_table('comentario')
    op.drop_table('post')
    op.drop_table('enquete')
    op.drop_table('usuario')
    # ### end Alembic commands ###
